#!/bin/bash
#
# Update CDT'23 in guillaumeportails.github.io

dst=cdt23

for f in \
	index.html \
	carte.js \
	drive.js \
	flex.css \
	icon-*.png \
	leaflet-distance-marker.css \
	leaflet-distance-marker.js \
	leaflet.filelayer.js \
	leaflet.geometryutil.d.ts \
	leaflet.geometryutil.js \
	logo.png \
	tracks
do
  mkdir -p $dst/$(dirname $f)
  e=${f##*.}
  if [[ "$e" == "js" || "$e" == "html" || "$e" == "css" ]]; then
    minify ../hikit/$f > $dst/$f
  else
    cp -r ../hikit/$f $dst
  fi
done

