#!/bin/bash
#
# Update CDT'23 in guillaumeportails.github.io

dst=cdt23
src=../hikit

(cd $src; ./build.sh)

# Minify carte
minify -b -o $dst/carte.js  $src/tracks/*.js $src/carte.js


# Minify others
for f in \
	index.html \
	drive.js \
	flex.css \
	icon-*.png \
	leaflet.filelayer.js \
	logo.png
do
  mkdir -p $dst/$(dirname $f)
  e=${f##*.}
  if [[ "$e" == "js" || "$e" == "html" || "$e" == "css" ]]; then
    echo "Minifying $f"
    minify $src/$f > $dst/$f
  else
    echo "Copying   $f"
    cp -r $src/$f $dst
  fi
done

ls -lR cdt23

